### PR TITLE
Updated centos.yml and debian.yml

### PR DESCRIPTION
**Pull request by claudineimatos**
* Skip SCSI tasks on AWS EC2 since it does not use SCSI on HVM instances

### CODE REVIEW

**Comment by mrlesmithjr** [comment]
@claudineimatos Thanks for the PR but I am confused on why you are referencing `iSCSI` here. Was this a typo when it should be `SCSI`? Maybe a bit more clarification on this would be much appreciated.

Thanks again!

**Comment by claudineimatos** [comment]
> @claudineimatos Thanks for the PR but I am confused on why you are referencing `iSCSI` here. Was this a typo when it should be `SCSI`? Maybe a bit more clarification on this would be much appreciated.
> 
> Thanks again!

Sorry, my mistake. It's actually SCSI.

**Comment by mrlesmithjr** [comment]
@markgoddard Thoughts on this one as well?

**Comment by markgoddard** [comment]
@claudineimatos is there an actual failure on AWS, or are you just looking to speed up the run by skipping tasks? Is there a possibility we might miss SCSI devices on an AWS bare metal instance?

**Comment by claudineimatos** [comment]
> @claudineimatos is there an actual failure on AWS, or are you just looking to speed up the run by skipping tasks? Is there a possibility we might miss SCSI devices on an AWS bare metal instance?

The task fails with the following error:

`
TASK [mrlesmithjr.manage-lvm : centos | rescanning for new disks] 
fatal: [hostname]: FAILED! => {"changed": false, "cmd": ["/usr/bin/rescan-scsi-bus.sh"], "delta": "0:00:00.042256", "end": "2019-10-24 08:22:51.094977", "msg": "non-zero return code", "rc": 1, "start": "2019-10-24 08:22:51.052721", "stderr": "cat: /sys/class/scsi_host/host/proc_name: No such file or directory", "stderr_lines": ["cat: /sys/class/scsi_host/host/proc_name: No such file or directory"], "stdout": "No SCSI host adapters found in sysfs", "stdout_lines": ["No SCSI host adapters found in sysfs"]}
`

I haven't tought about AWS bare metal but it's certainly the minority of cases. Anyway, it could be better to have a check to ensure the host has scsi enabled.

**Comment by markgoddard** [comment]
> > @claudineimatos is there an actual failure on AWS, or are you just looking to speed up the run by skipping tasks? Is there a possibility we might miss SCSI devices on an AWS bare metal instance?
> 
> The task fails with the following error:
> 
> `TASK [mrlesmithjr.manage-lvm : centos | rescanning for new disks] fatal: [hostname]: FAILED! => {"changed": false, "cmd": ["/usr/bin/rescan-scsi-bus.sh"], "delta": "0:00:00.042256", "end": "2019-10-24 08:22:51.094977", "msg": "non-zero return code", "rc": 1, "start": "2019-10-24 08:22:51.052721", "stderr": "cat: /sys/class/scsi_host/host/proc_name: No such file or directory", "stderr_lines": ["cat: /sys/class/scsi_host/host/proc_name: No such file or directory"], "stdout": "No SCSI host adapters found in sysfs", "stdout_lines": ["No SCSI host adapters found in sysfs"]}`
> 
> I haven't tought about AWS bare metal but it's certainly the minority of cases. Anyway, it could be better to have a check to ensure the host has scsi enabled.

+1, that would be a more general solution.

**Comment by Roxyrob** [comment]
Check for scsi adapter added for centos distro in #57.

This PR is for centos in general (vmware, aws ec2, probably bear metal but not tested). Check must be ported to debian based distros code.

**Pull request closed without merging**
